name: Build and deploy Angular app to Azure Web App - tiny-url-fe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          npm install
          npm install -g @angular/cli@20.0.0
          ng build --configuration production

      - name: Build Angular app
        run: npm run build --prod

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: ./angular-dist

      - name: Unzip artifact
        run: unzip ./angular-dist/angular-dist.zip -d ./angular-dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tiny-url-47
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./angular-dist
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4A4C00487954D57B13E879D86B7018B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22B0F19DC700466F9F06066AE95E75E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBA3ADBB34A549D18A587F6D6A2CC59B }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4A4C00487954D57B13E879D86B7018B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22B0F19DC700466F9F06066AE95E75E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBA3ADBB34A549D18A587F6D6A2CC59B }}

      - name: Deploy Angular build to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tiny-url-fe'
          slot-name: 'Production'
          package: dist/
